### ISSUE TITLE
Отображение контента в блоке mobile-block

### ISSUE THREAD

**Issue by AlexShyshkov** [AlexShyshkov/InteriorHomePage#22]
С помощью авокод проверь высоту блока mobile-block (должна быть 516рх), проверь расстояния и отступы между элементами в блоке.
После проверь отображение контента в блоке - элементы наползают друг на друга из-за свойства height class="slider-header", которое применено для заголовка <h2 class="slider-header">Find. Follow. <br> Favorite.</h2>

N.B. если убрать в class="slider-header" свойство height - меняется отображение контента в слайдере. 
Если необходимо сделай css стили для блока mobile-block

**Comment by Shih-tzuco** [comment]
Edited mobile block
