### ISSUE TITLE
Input width

### ISSUE THREAD

**Issue by AlexShyshkov** [AlexShyshkov/InteriorHomePage#28]
Ширина элемента input в блоке email должна быть такой же, как и ширина блока с текстом email-text, а также края элемента input не должны выходить за границы email-text (см. макет).

**Comment by Shih-tzuco** [comment]
Edited Input block

**Comment by AlexShyshkov** [comment]
В браузере EDGE баг сохраняется - проверить поддержку стилей, использовать вендорные префиксы
![Знімок екрана (71)](https://user-images.githubusercontent.com/36740943/81102785-cd9fa400-8f18-11ea-9792-38f70562ae6c.png)

**Comment by Shih-tzuco** [comment]
Edited input block, onfocus and value
