### ISSUE TITLE
Scroll up button

### ISSUE THREAD

**Issue by AlexShyshkov** [AlexShyshkov/InteriorHomePage#29]
Используя скрипт и стили (черновой вариант) создать элемент scroll up button, задать стили в общей тематике, связать со скриптом с помощью атрибута id

**Comment by Shih-tzuco** [comment]
Added Scroll Up

**Comment by AlexShyshkov** [comment]
Увеличь размер кнопки и сдвинь позицию элемента влево - минимум 50-100рх от правого края страницы

**Comment by Shih-tzuco** [comment]
Edited size and moved position
